version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-network

  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - mern-network

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db-data:/var/lib/mongodb/data
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  db-data: