version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: react-ui
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      -mern-network

  backend:
    build: ./backend
    container_name: node-api
    restart: always
    ports:
      - "5000:5000"
    # environment:
    #   - MONGO_URI=mongodb+srv://username:password@cluster0.wyjfaja.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    #   - CHATGPT_API_KEY=SECRET_KEY
    depends_on:
      - database
    networks:
      -mern-network

  database:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - home/SPE/Final_Project/SPE-Final-Project/mongo-data:/data/db
    networks:
      -mern-network

networks:
  mern-network:
    driver: bridge