version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    # environment:
    #   - MONGO_URI=mongodb+srv://aditisingh0409:RqpopGmLplZIwA9E@cluster0.wyjfaja.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    #   - CHATGPT_API_KEY=sk-proj-DI2GPKyWy1KJ2JQN0MeaT3BlbkFJdRQ5iJcEs0O3U2xgMUpD
    depends_on:
      - database

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: