- hosts: localhost
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Clone project repository
      git:
        repo: 'https://github.com/aditisingh0409/SPE-Final-Project.git'
        dest: /home/your_username/SPE-Final-Project

    - name: Start Docker Compose
      command: docker-compose up -d
      args:
        chdir: /home/your_username/SPE-Final-Project