- name: Deploy docker images
  hosts: localhost
  become: yes
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Clone project repository
      git:
        repo: 'https://github.com/aditisingh0409/SPE-Final-Project.git'
        dest: /home/SPE/Final_Project/SPE-Final-Project

    - name: Start Docker Compose
      command: docker-compose up -d --build
      args:
        chdir: /home/SPE/Final_Project/SPE-Final-Project
      
    - name: Prune unwanted images
      command: docker image prune --force